name: Deploy Frontend to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Show commit
        run: |
          echo "Commit:"
          git rev-parse HEAD
          git log -1 --oneline

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Clean install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Show dist
        run: ls -la dist

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: buyersectionapp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./dist
          clean: true